### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz.github.io#1]
@jdegoes Are you able to give me owner permissions to this repo? (for scalaz/scalaz#1897)

**Comment by xuwei-k** [comment]
done

![e174f8b3-f368-4a62-92d1-b15bb074d74f](https://user-images.githubusercontent.com/389787/41824928-688f1042-7853-11e8-8266-db03fb3ed09a.jpeg)

**Comment by NeQuissimus** [comment]
Thank you!
